### ISSUE TITLE
Outgoing call to number does not work

### ISSUE THREAD

**Issue by topwebtek7** [plivo/plivo-web-sdk2-examples#27]
How can i make outbound call works to random numbers? It redirect to answer endpoint back when dial random number(it converts to sip endpoint when dial just numbers - not plivo number).
Please help me to resolve this asap.

**Comment by anasahmed142** [comment]
hey topwebtek7 im also having this error SIP/2.0 401 Unauthorized and when i dial SIP/2.0 407 Proxy Authentication Required i did not know what to do i did the same thing can any one help me

**Comment by eniyavanm** [comment]
@topwebtek7 @anasahmed142 

Please write to support@plivo.com
