### ISSUE TITLE
No sound during the call when receiving in browser

### ISSUE THREAD

**Issue by menhalom** [plivo/plivo-web-sdk2-examples#28]
Hello Team,

We are using Plivo SDK to establish call between android app to browser between two sip endpoints.

Problem is that after receiving incoming call on browser, there is no sound during ongoing call.

Note:

 When call comes to browser , I can listen incoming ringtone.

Please. help me to get this done.

Waiting for  your feedback.

**Comment by eniyavanm** [comment]
@menhalom  Please write support@plivo.com
